# theme configuration
logo_url: https://embed.widencdn.net/img/widen/c17yrvuaac/400px@2x/Widen Engineering White Logo.png?u=mcuc7i
header_background_url: https://embed.widencdn.net/img/widen/m4ml1kuspv/exact/1680x90_Engineering Blog Banner.png?keep=c&crop=yes&u=ksmgip
twitter_username: widendev
github_widen: https://github.com/widen
github_repository: https://github.com/widen/jekyll-theme-guardian
google_analytics_code:
disqus_shortname:
